import type { MenuItem } from './types';

export const SALTY_TAPIOCAS: MenuItem[] = [
  {
    id: 14,
    name: 'BIJÚ DO NORTE',
    description: 'GOMA DE TAPIOCA COM OU SEM MANTEIGA.',
    images: [{ url: 'https://i.postimg.cc/J4wJnB34/beiju-of-tapioca-cassava-based-dish-typical-of-the-northeastern-region-of-brazil-now-consumed.webp', isMain: true }],
    price: 'R$ 4,00',
  },
  {
    id: 15,
    name: 'COMUM',
    description: 'GOMA DE TAPIOCA COM COCO RALADO.',
    images: [{ url: 'https://i.postimg.cc/52K2Xhcy/COMUM.avif', isMain: true }],
    price: 'R$ 7,00',
  },
  {
    id: 16,
    name: 'QUEIJO 1',
    description: 'MUSSARELA E MANTEIGA.',
    images: [{ url: 'https://i.postimg.cc/P5CkRNcQ/800-62365c6da6e6a.jpg', isMain: true }],
    price: 'R$ 9,00',
  },
  {
    id: 17,
    name: 'QUEIJO 2',
    description: 'MUSSARELA, REQUEIJÃO, CHEDDAR E ORÉGANO.',
    images: [{ url: 'https://i.postimg.cc/Kjj983tQ/tapioca-queijo-mussarela-e1692444665554.jpg', isMain: true }],
    price: 'R$ 10,00',
  },
  {
    id: 18,
    name: 'QUEIJO BRANCO',
    description: 'QUEIJO MINAS RALADO, TOMATE E ORÉGANO.',
    images: [{ url: 'https://i.postimg.cc/ZnXLY7bK/comida-tipica-brasileira-de-tapioca-com-recheio-de-queijo-presunto-tomate-e-oregano-266402-296.jpg', isMain: true }],
    price: 'R$ 10,00',
  },
  {
    id: 19,
    name: 'MISTA 1',
    description: 'MUSSARELA, PRESUNTO E MANTEIGA.',
    images: [{ url: 'https://i.postimg.cc/9fvT7R3q/MISTA-1.avif', isMain: true }],
    price: 'R$ 10,00',
  },
  {
    id: 20,
    name: 'MISTA 2',
    description: 'MUSSARELA, PRESUNTO, MANTEIGA, CHEDDAR, REQUEIJÃO E ORÉGANO.',
    images: [{ url: 'https://i.postimg.cc/sDXX3jqS/tapioca-recheada-com-tapioca-brasileira-de-frango-434193-1156.jpg', isMain: true }],
    price: 'R$ 10,00',
  },
  {
    id: 21,
    name: 'FRANGO',
    description: 'MANTEIGA, FRANGO DESFIADO, MUSSARELA, REQUEIJÃO, CHEDDAR E ORÉGANO.',
    images: [{ url: 'https://i.postimg.cc/MpxHQ7rn/Tapioca-de-frango-1.jpg', isMain: true }],
    price: 'R$ 10,00',
  },
  {
    id: 22,
    name: 'FRANGO MISTO',
    description: 'MANTEIGA, FRANGO DESFIADO, MUSSARELA, PRESUNTO, REQUEIJÃO, CHEDDAR E ORÉGANO.',
    images: [{ url: 'https://i.postimg.cc/65n9W8cm/SITE-9-1024x1024.png', isMain: true }],
    price: 'R$ 10,00',
  },
  {
    id: 23,
    name: 'CALABRESA',
    description: 'MANTEIGA, CALABRESA MOÍDA, MUSSARELA, REQUEIJÃO, CHEDDAR E ORÉGANO.',
    images: [{ url: 'https://i.postimg.cc/bJt5xtsW/f0302218-c085-457a-9d93-bf96a51153da.jpg', isMain: true }],
    price: 'R$ 10,00',
  },
  {
    id: 24,
    name: 'SALAME',
    description: 'MANTEIGA, SALAME FATIADO, MUSSARELA, REQUEIJÃO, CHEDDAR E ORÉGANO.',
    images: [{ url: 'https://i.postimg.cc/Bb3m2wWB/8-receitas-de-tapioca-com-queijo-para-um-lanche-saudavel.png', isMain: true }],
    price: 'R$ 10,00',
  },
  {
    id: 25,
    name: 'PERU',
    description: 'MANTEIGA, PEITO DE PERU FATIADO, E MUSSARELA COM OU SEM ORÉGANO.',
    images: [{ url: 'https://i.postimg.cc/7hL2vg0s/f2643850-e0d4-4fa8-8f7a-fc9cf6b92bb6.jpg', isMain: true }],
    price: 'R$ 10,00',
  },
  {
    id: 26,
    name: 'PERU ESPECIAL',
    description: 'MANTEIGA, PEITO DE PERU FATIADO, MUSSARELA, REQUEIJÃO, CHEDDAR COM OU SEM ORÉGANO.',
    images: [{ url: 'https://i.postimg.cc/vHg4W8zt/Tapioca-recheada.jpg', isMain: true }],
    price: 'R$ 12,00',
  },
  {
    id: 27,
    name: 'PERU FIT',
    description: 'QUEIJO MINAS RALADO, PEITO DE PERU, TOMATE E ORÉGANO.',
    images: [{ url: 'https://i.postimg.cc/QNRTYWV2/cc20b1417ab798601b733951625b4928d1edc138-JPG.webp', isMain: true }],
    price: 'R$ 12,00',
  },
  {
    id: 28,
    name: 'MODA DA CASA ESPECIAL',
    description: 'MANTEIGA, MUSSARELA, FRANGO DESFIADO, PRESUNTO, CALABRESA, CHEDDAR, REQUEIJÃO E ORÉGANO.',
    images: [{ url: 'https://i.postimg.cc/fbpzWY43/9-5c588fecda5fa.jpg', isMain: true }],
    price: 'R$ 12,00',
    rating: 5,
  },
  {
    id: 29,
    name: 'PIZZA',
    description: 'MANTEIGA, MUSARELA, TOMATE FATIADO, REQUEIJÃO E ORÉGANO.',
    images: [{ url: 'https://i.postimg.cc/8cDVsHZS/comida-tipica-brasileira-de-tapioca-com-recheio-de-queijo-presunto-tomate-e-oregano-266402-296.jpg', isMain: true }],
    price: 'R$ 10,00',
  },
  {
    id: 30,
    name: 'CARNE SECA',
    description: 'MANTEIGA, MUSSARELA, CARNE SECA DESFIADA, REQUEIJÃO E ORÉGANO.',
    images: [{ url: 'https://i.postimg.cc/YqnJwMBc/QBHHRIQKYNE2-PPSN32-N2-BASA4-U.jpg', isMain: true }],
    price: 'R$ 13,00',
  },
  {
    id: 31,
    name: 'CALABRESA BOVINA',
    description: 'MANTEIGA, CALABRESA BOVINA MOÍDA, MUSSARELA, REQUEIJÃO, CHEDDAR E ORÉGANO.',
    images: [{ url: 'https://i.postimg.cc/WbkMswQv/receita-tapioca-com-linguica.jpg', isMain: true }],
    price: 'R$ 10,00',
  },
  {
    id: 32,
    name: 'BAURU',
    description: 'MANTEIGA, MUSSARELA, PRESUNTO, TOMATE FATIADO, REQUEIJÃO, CHEDDAR E ORÉGANO.',
    images: [{ url: 'https://i.postimg.cc/wBytkqgK/tapioca-de-queijo-e-presunto.png', isMain: true }],
    price: 'R$ 10,00',
  },
  {
    id: 33,
    name: 'BACON',
    description: 'MUSARELA, BACON E ORÉGANO.',
    images: [{ url: 'https://i.postimg.cc/52RcV1vX/Tapioca-de-queijo-e-bacon-1.png', isMain: true }],
    price: 'R$ 12,00',
  },
  {
    id: 34,
    name: 'BRÓCOLIS',
    description: 'QUEIJO MINAS RALADO, BRÓCOLIS, REQUEIJÃO E ORÉGANO.',
    images: [{ url: 'https://i.postimg.cc/6QYHChWm/BR-COLIS.jpg', isMain: true }],
    price: 'R$ 12,00',
  },
  {
    id: 35,
    name: 'CHEDDAR',
    description: 'MUSSARELA, MANTEIGA, PEITO DE FRANGO FATIADO, CHEDDAR E BATATA PALHA.',
    images: [{ url: 'https://i.postimg.cc/N0jhhF5K/181acada-c59c-4f10-8298-b352c4daa950.jpg', isMain: true }],
    price: 'R$ 10,00',
  },
  {
    id: 36,
    name: 'CAIPIRA',
    description: 'MANTEIGA, MUSSARELA, FRANGO DESFIADO E MILHO VERDE.',
    images: [{ url: 'https://i.postimg.cc/kGrh5gXX/tapioca-natto-1562x738.jpg', isMain: true }],
    price: 'R$ 10,00',
  },
  {
    id: 37,
    name: 'OVO ESPECIAL',
    description: 'MANTEIGA, MUSARELA, PRESUNTO, OVO, FRANGO, REQUEIJÃO, CHEDDAR, ORÉGANO.',
    images: [{ url: 'https://i.postimg.cc/L4zxTR8g/9217346f41a5b7e8e45bd1d2bf97a850-XL.jpg', isMain: true }],
    price: 'R$ 12,00',
  },
  {
    id: 38,
    name: 'PORTUGUESA',
    description: 'MANTEIGA, MUSARELA, PRESUNTO, OVO, MILHO VERDE, REQUEIJÃO, AZEITE E ORÉGANO.',
    images: [{ url: 'https://i.postimg.cc/RCQTtRgQ/355374-original.jpg', isMain: true }],
    price: 'R$ 12,00',
  }
];

export const SWEET_TAPIOCAS: MenuItem[] = [
  {
    id: 17,
    name: 'BEIJINHO',
    description: 'COCO RALADO COM LEITE CONDENSADO.',
    images: [
      { url: 'https://i.postimg.cc/cLNG8qQS/203262-original.jpg', isMain: true },
      { url: 'https://xamegobom.com.br/wp-content/uploads/2017/02/tapioca-com-leite-condensado1.jpg', isMain: false },
      { url: 'https://receitinhasdadani.com.br/wp-content/uploads/2022/07/Tapioca-com-leite-condensado-e-coco.jpg', isMain: false },
      { url: 'https://i.pinimg.com/originals/9b/12/c0/9b12c0854bbb7768d434e766b33c0eb2.jpg', isMain: false },
      { url: 'https://www.grupopq.com.br/wp-content/uploads/2021/02/Tapioca-coco-leitecondensado-1-1024x1024.jpg', isMain: false },
    ],
    price: 'R$ 8,00',
  },
  {
    id: 18,
    name: 'PRESTÍGIO',
    description: 'COCO RALADO, CHOCOLATE RALADO E LEITE CONDENSADO.',
    images: [
      { url: 'https://i.postimg.cc/qq023vMc/tapioca-doce-de-coco-ralado-com-leite-condensado.jpg', isMain: true },
    ],
    price: 'R$ 10,00',
  },
  {
    id: 19,
    name: 'MORANGO CREME',
    description: 'COCO RALADO, CREME DE MORANGO E LEITE CONDENSADO.',
    images: [
      { url: 'https://www.estadao.com.br/resizer/v2/2Z3ZSSS27BAJ3CKSYRGUTAGC6Y.jpg?quality=80&auth=a5f577569ac49f121ff64877124c6eccb08c181f84e14bd90ad174682d049e82&width=720&height=410&smart=true', isMain: true },
    ],
    price: 'R$ 8,00',
  },
  {
    id: 20,
    name: 'QUEIJADINHA',
    description: 'COCO RALADO, MUSSARELA E LEITE CONDENSADO',
    images: [
      { url: 'https://guiadacozinha.com.br/wp-content/uploads/2004/01/tapioca-de-leite-condensado-com-coco.jpg', isMain: true },
    ],
    price: 'R$ 10,00',
  },
  {
    id: 21,
    name: 'SENSAÇÃO',
    description: 'COCO RALADO, CHOCOLATE RALADO, CREME DE MORANGO E LEITE CONDENSADO.',
    images: [
      { url: 'https://guiadacozinha.com.br/wp-content/uploads/2004/01/tapioca-de-morango-com-chocolate.jpg', isMain: true },
    ],
    price: 'R$ 10,00',
  },
  {
    id: 22,
    name: 'ROMEU E JULIETA',
    description: 'MUSSARELA, COCO RALADO, GOIABADA LÍQUIDA E LEITE CONDENSADO.',
    images: [
      { url: 'https://www.receitadevovo.com.br/_next/image?url=https://d2qcpt1idvpipw.cloudfront.net/recipes/2020/10/tapioca-com-queijo-e-goiabada.jpg&w=3840&q=75', isMain: true },
    ],
    price: 'R$ 10,00',
  },
  {
    id: 23,
    name: 'GOIABADA',
    description: 'COCO RALADO, GOIABADA LÍQUIDA E LEITE CONDENSADO',
    images: [
      { url: 'https://amodadoflavio.pt/ophaboah/2019/05/Tapioca-de-goiabada-com-queijo-creme.png', isMain: true },
    ],
    price: 'R$ 9,00',
  },
  {
    id: 24,
    name: 'PAÇOCA AMENDOIM',
    description: 'COCO RALADO, PAÇOCA POLVILHADA E LEITE CONDENSADO.',
    images: [
      { url: 'https://img-global.cpcdn.com/recipes/be81fe3f6416e6ce/240x320cq80/photo.jpg', isMain: true },
    ],
    price: 'R$ 10,00',
  },
  {
    id: 25,
    name: 'BANANA',
    description: 'BANANA FATIADA, LEITE CONDENSADO, COCO RALADO E CANELA.',
    images: [
        { url: 'https://t4.ftcdn.net/jpg/14/80/75/31/360_F_1480753173_3ZMaBZASxHWHHUUzpGLebc1BWaoFakCr.jpg', isMain: true },
    ],
    price: 'R$ 10,00',
  },
  {
    id: 26,
    name: 'BANANA COM NUTELLA',
    description: 'BANANA FATIADA E NUTELLA.',
    images: [
        { url: 'https://receitasdepesos.com.br/wp-content/uploads/2023/08/shutterstock_1152917999.jpg', isMain: true },
        { url: 'https://s3-sa-east-1.amazonaws.com/deliveryon-uploads/products/imperio/30_5c58a760b2f3e.jpg', isMain: false },
        { url: 'https://app.cardapiodigital.net/dnizcafeebistro/5757-home_default/banana-cnutella.jpg', isMain: false },
    ],
    price: 'R$ 12,00',
  },
  {
    id: 27,
    name: 'MORANGO COM NUTELLA',
    description: 'MORANGO FATIADO E NUTELLA.',
    images: [
        { url: 'https://cozidoeassado.com/wp-content/uploads/2023/08/tapioca-de-nutella-e-morango.webp', isMain: true },
        { url: 'https://seguiareceita.com/wp-content/uploads/2024/01/Tapioca-de-Nutella-e-Morango-1024x457.jpg', isMain: false },
        { url: 'https://media-cdn.tripadvisor.com/media/photo-o/10/3d/07/a8/tapioca-de-nutella-com.jpg', isMain: false },
        { url: 'https://s3-sa-east-1.amazonaws.com/deliveryon-uploads/products/imperio/27_5c589940ab310.jpg', isMain: false },
        { url: 'https://arcadasportofado.pt/receitas/wp-content/uploads/tapioca-de-nutella-com-morango.jpg', isMain: false },
    ],
    price: 'R$ 14,00',
  },
  {
    id: 28,
    name: 'TAPIOCA COM NUTELLA',
    description: 'GOMA DE TAPIOCA COM NUTELA',
    images: [
        { url: 'https://imagens.jotaja.com/produtos/6994ecaa-2c90-473e-9be1-75b2c341c1af.jpg', isMain: true },
        { url: 'https://media.gettyimages.com/id/997268460/es/foto/tapioca-nutella.jpg?s=612x612&w=0&k=20&c=TX_ZY8YUY7vHNOnSfPfdLu4IsSoMhgKxVSQGlLdxrOc=', isMain: false },
        { url: 'https://blog.novasafra.com.br/wp-content/uploads/2020/09/23934764-780x400.jpeg', isMain: false },
        { url: 'https://media-cdn.tripadvisor.com/media/photo-o/1b/67/12/df/tapioca-de-nutella-com.jpg', isMain: false },
        { url: 'https://media.gettyimages.com/id/639301620/photo/tapioca.jpg?s=612x612&w=0&k=20&c=iuishg8xM8-o3VDBNbvJFL8yw7ixPDq4QB3DamnJKd8=', isMain: false },
    ],
    price: 'R$ 11,00',
  },
];

export const BEBIDAS_E_OUTROS: MenuItem[] = [
    {
        id: 29,
        name: 'Coca-Cola Lata 350ml',
        description: 'O sabor clássico e refrescante da Coca-Cola.',
        images: [{ url: 'https://i.postimg.cc/4Kjrw4XT/coca-cola-lata-350-ml-1.jpg', isMain: true }],
        price: 'R$ 6,00',
    },
    {
        id: 30,
        name: 'Coca-Cola (Mini) 200ml',
        description: 'A dose perfeita de Coca-Cola para matar a sua sede.',
        images: [{ url: 'https://i.postimg.cc/rmdyGKJL/D-Q-NP-2-X-664808-MLB45065083759-032021-V.webp', isMain: true }],
        price: 'R$ 5,00',
    },
    {
        id: 31,
        name: 'Coca-Cola Zero (Mini) 200ml',
        description: 'Todo o sabor da Coca-Cola, sem açúcar.',
        images: [{ url: 'https://i.postimg.cc/KYjmFRCS/ref-coca-cola-mini-pet-zero-200ml-78933873-jpg.webp', isMain: true }],
        price: 'R$ 5,00',
    },
    {
        id: 32,
        name: 'Guaraná Antarctica Lata 350ml',
        description: 'O sabor original do Brasil.',
        images: [{ url: 'https://i.postimg.cc/gcVFCVrg/1xg.jpg', isMain: true }],
        price: 'R$ 6,00',
    },
    {
        id: 33,
        name: 'Fanta Laranja Lata 350ml',
        description: 'Refrescante e borbulhante sabor de laranja.',
        images: [{ url: 'https://i.postimg.cc/9FLS2J2P/fanta-laranja-lata-350ml-39-1-53815cf3fdd217edfbcc3a175e12d14d.png', isMain: true }],
        price: 'R$ 6,00',
    },
    {
        id: 34,
        name: 'Fanta Uva Lata 350ml',
        description: 'O delicioso e irresistível sabor da uva.',
        images: [{ url: 'https://i.postimg.cc/FsCP8zbz/refrigerante-uva-fanta-lata-350ml-713.jpg', isMain: true }],
        price: 'R$ 6,00',
    },
    {
        id: 35,
        name: 'Soda Limonada Antarctica Lata 350ml',
        description: 'Leve e cítrico, para refrescar seu dia.',
        images: [{ url: 'https://i.postimg.cc/zvXjPYV6/image.jpg', isMain: true }],
        price: 'R$ 6,00',
    },
    {
        id: 36,
        name: 'Dolly Guaraná 350ml',
        description: 'O guaraná do dollynho, seu amiguinho.',
        images: [{ url: 'https://i.postimg.cc/jqgQd9DF/D-Q-NP-2-X-926074-MLB42338413436-062020-V.webp', isMain: true }],
        price: 'R$ 5,00',
    },
    {
        id: 37,
        name: 'Dolly Cola 350ml',
        description: 'Sabor cola para todos os gostos.',
        images: [{ url: 'https://i.postimg.cc/kGzbN08R/D-Q-NP-2-X-747319-MLB42338093454-062020-V.webp', isMain: true }],
        price: 'R$ 5,00',
    },
    {
        id: 38,
        name: 'Dolly Limão 350ml',
        description: 'Refrescância e sabor de limão.',
        images: [{ url: 'https://i.postimg.cc/FF7DMcp6/foto-product.jpg', isMain: true }],
        price: 'R$ 5,00',
    },
    {
        id: 39,
        name: 'Suco de Maracujá Del Valle 290ml',
        description: 'Néctar de maracujá, sabor da fruta.',
        images: [{ url: 'https://i.postimg.cc/gcCq17r1/D-Q-NP-2-X-754681-MLB88251857533-072025-V.webp', isMain: true }],
        price: 'R$ 7,00',
    },
    {
        id: 40,
        name: 'Suco de Uva Del Valle 290ml',
        description: 'Néctar de uva, doçura e sabor.',
        images: [{ url: 'https://i.postimg.cc/26BLwzdv/image-94034-1-1-1-1-1.jpg', isMain: true }],
        price: 'R$ 7,00',
    },
    {
        id: 41,
        name: 'Suco de Pêssego Del Valle 290ml',
        description: 'Néctar de pêssego, suave e delicioso.',
        images: [{ url: 'https://i.postimg.cc/LsJJ9HWM/image.webp', isMain: true }],
        price: 'R$ 7,00',
    },
    {
        id: 42,
        name: 'Suco de Manga Del Valle 290ml',
        description: 'Néctar de manga, o sabor tropical.',
        images: [{ url: 'https://i.postimg.cc/CKnKycZq/suco-del-valle-nectar-de-manga-290ml-6802.jpg', isMain: true }],
        price: 'R$ 7,00',
    },
    {
        id: 43,
        name: 'Água Mineral sem Gás 500ml',
        description: 'Para hidratar a qualquer momento.',
        images: [{ url: 'https://i.postimg.cc/bwWzR1m5/agua-mineral-sem-gas-crystal-500ml-1.jpg', isMain: true }],
        price: 'R$ 3,00',
    },
    {
        id: 44,
        name: 'Água Mineral com Gás 500ml',
        description: 'Refrescância com um toque de gás.',
        images: [{ url: 'https://i.postimg.cc/Fs15n7kQ/D-Q-NP-2-X-661013-MLB80259151736-112024-V-agua-mineral-natural-com-gas-crystal-pack-12-unidades-500ml.webp', isMain: true }],
        price: 'R$ 4,00',
    },
    {
        id: 45,
        name: 'Goma de Tapioca 1kg',
        description: 'Goma de tapioca caseira. Leve a Delegusty para sua casa! Você vai ter a chance de dar um toque especial às suas receitas, seja no almoço, lanche da tarde ou jantar. Levou à frigideira? Está pronto! Solte a criatividade e crie recheios e acompanhamentos deliciosos.',
        images: [{ url: 'https://i.postimg.cc/2y7QQkm4/Fecula-de-Mandioca.jpg', isMain: true }],
        price: 'R$ 10,00',
    }
];